---
server:
  port: 9090
  contextPath: /SMIT
---
spring:
  profiles: prod, default
  mvc:
    view:
      suffix: html
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/planb
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.method: create-update
      show_sql: true
      format_sql: true
      
